export type DownloadItem = {
  id: number;
  title: string;
  link: string;
  kind: "magnet" | "torrent";
  startedAt: string;
  status: "started" | "failed" | "completed" | "paused";
  path?: string;
  tempPath?: string;
  finalPath?: string;
  finalized?: boolean;
  torrentId?: number;
  infoHash?: string;
  progressBytes?: number;
  totalBytes?: number;
  uploadedBytes?: number;
  state?: string;
  error?: string;
  downloadSpeed?: string;
  uploadSpeed?: string;
  timeRemaining?: string;
};
